spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crm?characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useUnicode=true
    username: root
    password: 123456

  freemarker:
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/views/
    charset: UTF-8

server:
  port: 8080
  servlet:
    context-path: /crm
pagehelper:
  helper-dialect: mysql
mybatis:
  type-aliases-package: com.yjxxt.crm.bean;com.yjxxt.crm.query;
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com:
      yjxxt:
        crm:
          mapper: debug
